services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: unless-stopped

    env_file:
      - ./apps/api/.env

    environment:
      NODE_ENV: production
      PORT: 5000
    networks: [planici_network]

  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${NEXT_PUBLIC_GOOGLE_CLIENT_ID:?Set the Google Client ID}
    restart: unless-stopped

    env_file:
      - ./apps/web/.env

    depends_on: [api]
    environment:
      NODE_ENV: production
      PORT: "3000"
      WEB_APP_URL: https://joaoizidoro.com
    networks: [planici_network]
  
  proxy:
    build: ./docker/proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/proxy/certs:/certs:ro
    depends_on: [web, api]
    restart: unless-stopped
    networks: [planici_network]

networks:
  planici_network: {}
