sonar.projectKey=planici-monorepo
sonar.projectName=Planici
sonar.sourceEncoding=UTF-8

sonar.sources=apps,packages

sonar.tests=apps,packages

sonar.test.inclusions=\
**/*.spec.ts,\
**/*.spec.tsx,\
**/*.test.ts,\
**/*.test.tsx,\
**/__tests__/**/*

soar.exclusions=\
**/*.spec.ts,\
**/*.spec.tsx,\
**/*.test.ts,\
**/*.test.tsx,\
**/__tests__/**,\
**/node_modules/**,\
**/.next/**,\
**/dist/**,\
**/coverage/**,\
**/.turbo/**
