sonar.organization=angeluciel
sonar.projectKey=planici
sonar.projectName=Planici
sonar.sourceEncoding=UTF-8

sonar.sources=apps,packages

sonar.tests=apps,packages

sonar.test.inclusions=\
**/*.spec.ts,\
**/*.spec.tsx,\
**/*.test.ts,\
**/*.test.tsx,\
**/__tests__/**/*

sonar.exclusions=\
**/*.spec.ts,\
**/*.spec.tsx,\
**/*.test.ts,\
**/*.test.tsx,\
**/__tests__/**,\
**/node_modules/**,\
**/.next/**,\
**/dist/**,\
**/coverage/**,\
**/.turbo/**

sonar.javascript.lcov.reportPaths=apps/api/coverage/lcov.info